[[plugins]]
repo = 'romgrk/barbar.nvim'
on_source = 'lightline.vim'
depends = 'nvim-web-devicons' 
hook_add = '''
nnoremap <silent> <leader>1 :BufferGoto 1<CR>
nnoremap <silent> <leader>2 :BufferGoto 2<CR>
nnoremap <silent> <leader>3 :BufferGoto 3<CR>
nnoremap <silent> <leader>4 :BufferGoto 4<CR>
nnoremap <silent> <leader>5 :BufferGoto 5<CR>
nnoremap <silent> <leader>6 :BufferGoto 6<CR>
nnoremap <silent> <leader>7 :BufferGoto 7<CR>
nnoremap <silent> <leader>8 :BufferGoto 8<CR>
nnoremap <silent> <leader>9 :BufferGoto 9<CR>
nnoremap <silent> <leader>bj :BufferPick<CR>
nnoremap <silent> <leader>bp :BufferPin<CR>
nnoremap <silent> <leader>bc :BufferClose<CR>
nnoremap <silent> <leader>bC :BufferCloseAllButCurrentOrPinned<CR>
nnoremap <silent> <leader>bo :BufferOrderByLanguage<CR>
let bufferline = get(g:, 'bufferline', {})
let bufferline.auto_hide = v:true
let bufferline.closable = v:false
let bufferline.icons = 'numbers'
let bufferline.icon_pinned = 'P'
autocmd Init BufAdd * BufferOrderByLanguage
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons' 
