[[plugins]]
repo = 'akinsho/bufferline.nvim'
rev = 'v2.*'
depends = 'nvim-web-devicons'

hook_source = '''
lua << EOF
require("bufferline").setup {
  options = {
    numbers = "ordinal",
    close_icon = "",
    show_buffer_close_icons = false,
    enforce_regular_tabs = true,
    always_show_bufferline = false,
  }
}
EOF

autocmd Init BufAdd * BufferLineSortByExtension
'''

hook_add = '''
nnoremap <silent><leader>1 <Cmd>BufferLineGoToBuffer 1<CR>
nnoremap <silent><leader>2 <Cmd>BufferLineGoToBuffer 2<CR>
nnoremap <silent><leader>3 <Cmd>BufferLineGoToBuffer 3<CR>
nnoremap <silent><leader>4 <Cmd>BufferLineGoToBuffer 4<CR>
nnoremap <silent><leader>5 <Cmd>BufferLineGoToBuffer 5<CR>
nnoremap <silent><leader>6 <Cmd>BufferLineGoToBuffer 6<CR>
nnoremap <silent><leader>7 <Cmd>BufferLineGoToBuffer 7<CR>
nnoremap <silent><leader>8 <Cmd>BufferLineGoToBuffer 8<CR>
nnoremap <silent><leader>9 <Cmd>BufferLineGoToBuffer 9<CR>
nnoremap <silent><C-j> :BufferLineCycleNext<CR>
nnoremap <silent><C-k> :BufferLineCyclePrev<CR>
'''
