[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
depends = ['vim-js', 'yats.vim']
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'yuezk/vim-js'
on_ft = ['javascript']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript']
