[[plugins]]
repo = 'xiyaowong/nvim-transparent'
hook_add = '''
lua << EOF
require("transparent").setup({
  enable = true,
  extra_groups = {
    "GitGutterAdd",
    "GitGutterDelete",
    "GitGutterChange",
    "GitGutterChangeDelete",
  },
})
EOF
'''
