[[plugins]]
repo = 'xiyaowong/nvim-transparent'
hook_add = '''
set pumblend=30
set winblend=30
lua << EOF
require("transparent").setup({
  enable = true,
  extra_groups = "all",
  exclude = {
    "StatusLine",
    "Visual",
    "Search",
  },
})
EOF
'''
