[[plugins]]
repo = 'xiyaowong/nvim-transparent'
on_source = 'gruvbox-material'
hook_add = '''
lua << EOF
require("transparent").setup({
  enable = true,
  extra_groups = {
    -- barbar.nvim
    "BufferCurrent",
    "BufferCurrentIndex",
    "BufferCurrentSign",
    "BufferVisible",
    "BufferVisibleIndex",
    "BufferVisibleSign",
    "BufferInactive",
    "BufferInactiveIndex",
    "BufferInactiveSign",
    "BufferTabpages",
    "BufferTabpageFill",
  },
})
EOF
'''
