[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
    let s:deno_bin = exepath('deno')
    if !filereadable(s:deno_bin)
        execute '!curl -fsSL https://deno.land/x/install/install.sh | sh'
    endif
'''

[[plugins]]
repo = 'lambdalisue/guise.vim'

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
nmap <C-_> gcc
vmap <C-_> gc
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'gko/vim-coloresque'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
