[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
    nmap <C-_> gcc
    vmap <C-_> gc
'''

[[plugins]]
repo = 'tpope/vim-surround'
