[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = 'vimproc.vim'
hook_add = '''
  let g:quickrun_config = {}
  nnoremap <silent> <leader>r <cmd>QuickRun<CR>
'''

[[plugins]]
repo = 'github/copilot.vim'
on_event = [ 'InsertEnter', 'TextChangedI' ]

[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'CursorHold'
hook_add = 'let s:deno_bin = exepath("deno")'

# [[plugins]]
# repo = 'vim-denops/denops-shared-server.vim'
# hook_add = 'let g:denops_server_addr = "localhost:3456"'
# hook_done_update = 'call denops_shared_server#install()'

[[plugins]]
repo = 'lambdalisue/guise.vim'

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
  nmap <C-_> gcc
  vmap <C-_> gc
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
