[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'CursorHold'
hook_add = 'let s:deno_bin = exepath("deno")'

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = 'denops.vim'
on_event = 'TermOpen'

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'
on_post_source = 'denops.vim'

[[plugins]]
repo = 'github/copilot.vim'
on_event = [ 'InsertEnter', 'TextChangedI' ]

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
  nmap <C-_> gcc
  vmap <C-_> gc
'''

[[plugins]]
repo = 'machakann/vim-sandwich'
