[[plugins]]
repo = 'ziglang/zig.vim'
on_ft = 'zig'
hook_add = '''
  autocmd BufNewFile,BufRead *.zon setfiletype zig
  let g:zig_fmt_autosave = 0
'''

# [[plugins]]
# repo = 'iamcco/markdown-preview.nvim'
# on_ft = 'markdown'
# hook_post_update = 'sh -c "cd app && yarn install"'

# [[plugins]]
# repo = 'ellisonleao/glow.nvim'
# on_ft = 'markdown'
# hook_add = 'nnoremap <LocalLeader>p :Glow<CR>'
