[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = 'dart'
hook_source = '''
    let g:flutter_show_log_on_run = "tab"
    let g:flutter_autoscroll = 1
    nnoremap <LocalLeader>r :FlutterRun<CR>
    nnoremap <LocalLeader>q :FlutterQuit<CR>
    nnoremap <LocalLeader>t :FlutterTab<CR>
'''

