[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <leader>gs :Git<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
nnoremap <leader>gu :GitGutterUndoHunk<CR>
'''

[[plugins]]
repo = 'skanehira/gh.vim'
